# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-SPF_XS
version:      0.01
version_from: SPF_XS.pm
installdirs:  site
requires:
    Mail::SPF:                     0.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
