.TH "recvmail" "8" "" "" "Electronic Mail"
.SH "NAME"
.LP 
recvmail \- receive electronic mail
.SH "SYNOPSIS"
.LP 
recvmail [\-fhqv] [\-d \fIpath\fP] [\-u \fIuid\fP] [\-g \fIgid\fP] [\-i \fIaddress\fP] [\-p \fIport\fP] 
.SH "OPTIONS"
.TP 13
\fB\-d\fP \fIpath\fP
Directory to use as the root of the chroot(1) jail.
.TP 13
\fB\-f\fP
Run in the foreground.
.TP 13
\fB\-g\fP \fIgid\fP
Run under a different group ID.
.TP 13
\fB\-h\fP
Print a help message.
.TP 13
\fB\-i\fP \fIaddress\fP
Listen on a specific IPv4 \fIaddress\fP. 
.TP 13
\fB\-p\fP \fIport\fP
Listen on an alternate \fIport\fP.
.TP 13
\fB\-q\fP
Quiet; only print error messages to the log.       
.TP 13
\fB\-u \fIuid\fP
Run under a different user ID.
.TP 13
\fB\-v\fR
Verbose; increase the logging verbosity.
.SH "DESCRIPTION"
.LP 
Recvmail is an electronic mail transfer agent that receives mail from the network and delivers it to Maildir-formatted mailboxes.  
.br
.SH "STANDARDS"
.LP
RFC 2821 - Simple Mail Transport Protocol
.SH "BUGS"
.LP
Under heavy load, the server drops a small number of connections when running in
multithreaded mode. Less than 0.02 percent of connections exhibit problems starting up. Multiprocess mode is not affected by this problem.
.SH "AUTHORS"
.LP 
Mark Heily \<devel\@heily.com\>
.SH "SEE ALSO"
.LP 
sendmail(1)
.P
http\://recvmail.org
